### ISSUE TITLE
No longer builds with alpine:latest

### ISSUE THREAD

**Issue by MatrixCat3D** [rjnorthrow/m68k-toolchain#1]
I was trying to reproduce this build as you have documented it (to add vasm) but the build fails with alpine:latest, alpine:3.11, alpine:3.10, and alpine:3.9 - I suggest specifying alpine:3.8 for which it does indeed work.
https://github.com/rjnorthrow/m68k-toolchain/blob/2f1030cb64c3cadc21e2338aab70e60d834bc157/Dockerfile#L1

**Comment by rjnorthrow** [comment]
Added 'alpine:3.8' to ensure compatibility.
